<?xml version="1.0" encoding="UTF-8"?><testrun name="ComputeSalaryTest" project="Project" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="com.pcm.test.ComputeSalaryTest" time="2.374">
    <testcase name="findByNameTest" classname="com.pcm.test.ComputeSalaryTest" time="2.374">
      <error>javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: user lacks privilege or object not found: FIRSTNAME&#13;
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1365)&#13;
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1293)&#13;
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:317)&#13;
	at com.pcm.dao.EmployeeDAO.findByName(EmployeeDAO.java:83)&#13;
	at com.pcm.service.PayroleService.findByName(PayroleService.java:64)&#13;
	at com.pcm.test.ComputeSalaryTest.findByNameTest(ComputeSalaryTest.java:46)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:601)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: org.hibernate.exception.SQLGrammarException: user lacks privilege or object not found: FIRSTNAME&#13;
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:82)&#13;
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)&#13;
	at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:146)&#13;
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)&#13;
	at com.sun.proxy.$Proxy22.prepareStatement(Unknown Source)&#13;
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:147)&#13;
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:166)&#13;
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:145)&#13;
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1720)&#13;
	at org.hibernate.loader.Loader.doQuery(Loader.java:828)&#13;
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)&#13;
	at org.hibernate.loader.Loader.doList(Loader.java:2447)&#13;
	at org.hibernate.loader.Loader.doList(Loader.java:2433)&#13;
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2263)&#13;
	at org.hibernate.loader.Loader.list(Loader.java:2258)&#13;
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:470)&#13;
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)&#13;
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)&#13;
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1215)&#13;
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)&#13;
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:284)&#13;
	... 31 more&#13;
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: FIRSTNAME&#13;
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)&#13;
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)&#13;
	at org.hsqldb.jdbc.JDBCPreparedStatement.&lt;init&gt;(Unknown Source)&#13;
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:601)&#13;
	at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:138)&#13;
	... 49 more&#13;
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: FIRSTNAME&#13;
	at org.hsqldb.error.Error.error(Unknown Source)&#13;
	at org.hsqldb.error.Error.error(Unknown Source)&#13;
	at org.hsqldb.ExpressionColumn.checkColumnsResolved(Unknown Source)&#13;
	at org.hsqldb.QueryExpression.resolve(Unknown Source)&#13;
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)&#13;
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)&#13;
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)&#13;
	at org.hsqldb.Session.compileStatement(Unknown Source)&#13;
	at org.hsqldb.StatementManager.compile(Unknown Source)&#13;
	at org.hsqldb.Session.execute(Unknown Source)&#13;
	... 56 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
